apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
  - ./infra/k8s/*
build:
  googleCloudBuild:
    projectId: ticketing-dev-445210
  artifacts:
  - image: us.gcr.io/ticketing-dev-445210/auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .
